### ISSUE TITLE
No audio on calls

### ISSUE THREAD

**Issue by damencho** [jitsi/jigasi#29]
Creating an issue to track progress of fixing jigasi to work with latest jvb verison.
Since latest changes in videobridge jigasi stopped working. It used to work without DTLS, which seems a problem now. In order to investigate and fix it. jigasi needs first to be mavenized. A branch is pushed with on going work on that effort. In my todo list there are few jitsi bundles that need to be mavenized:
protocol-sip.jar

packetlogging.jar
httputil.jar
whack.jar
argdelegation-service.jar

hid-service.jar
hid.jar

After finishing that and having a build using maven we can continue with investigating the problem.

**Comment by ibauersachs** [comment]
I would assume that this also depends on https://github.com/jitsi/jitsi/issues/193

**Comment by damencho** [comment]
Thanks, yeah that is correct.

**Comment by mcguinn** [comment]
Can you add this to list of no-audio as it relates to SIP-only conferences and SBCs that wont relay media until they see media from both side of the call.
https://github.com/jitsi/jigasi/issues/30

**Comment by petervnv** [comment]
I also wanted to confirm I'm having the same no audio behaviour on latest jvb, jitmeet and jigasi debian 8 nightly packages.

**Comment by arag00rn** [comment]
We are facing same issues here:

cat /etc/debian_version 8.4

ii  jicofo                         1.0-252-1                   amd64        JItsi Meet COnference FOcus
ii  jigasi                         1.0-99                      amd64        Jitsi Gateway for SIP
ii  jitsi-meet                     1.0.979-1                   all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody             1.0.979-1                   all          Prosody configuration for Jitsi Meet
ii  jitsi-videobridge              727-1                       amd64        WebRTC compatible Selective Forwarding Unit (SFU)

**Comment by destroy-everything** [comment]
+1

**Comment by mrgloba** [comment]
I have same issues:

cat /etc/debian_version 8.4

ii  jicofo 1.0-254-1 amd64
ii  jigasi 1.0-99 amd64
ii  jitsi-meet 1.0.985-1 all
ii  jitsi-meet-prosody 1.0.985-1 all
ii  jitsi-videobridge 729-1 amd64

In jigasi log
```
SEVERE: [602] net.sf.fmj.media.Log.error()   Unable to handle format: LINEAR, 48000.0 Hz, 16-bit, Mono, LittleEndian, Signed
SEVERE: [602] net.sf.fmj.media.Log.error() Failed to prefetch: net.sf.fmj.media.ProcessEngine@77ad3557
SEVERE: [601] net.sf.fmj.media.Log.error() Error: Unable to prefetch net.sf.fmj.media.ProcessEngine@77ad3557
```

**Comment by petervnv** [comment]
Has there been any progress on this?

What's the latest version of jvb that still works with jigasi?

**Comment by damencho** [comment]
For the jvb version you can check the mailinglist, there were some reports from users. I've been trying to mavenize it so we can bring jigasi up to date and fix it. But I'm having some issues currently while starting it and I'm debugging it currently.

**Comment by petervnv** [comment]
Thanks damencho. I'll take a look through the list.

Cheers

**Comment by petervnv** [comment]
Hi guys,

I see the issue is now closed, but I still have 1 question.

I see you disabled ZRTP in src/main/java/org/jitsi/jigasi/JvbConference.java
and enabled DTLS by default.

I have tested it and now indeed audio is back, although it is not ZRTP
encrypted.

I need ZRTP encryption so how can I enable it again? Do I have to compile
from source (I'm using debian nightly packages) and set
DEFAULT_SIPZRTP_ATTRIBUTE to TRUE again or is there a parameter I can add
to sip.communicator.properties to re-enable ZRTP without having to compile
from source?

Cheers,
Peter

**Comment by petervnv** [comment]
Ok, I've done some more testing. If I enable ZRTP manually I get the old behaviour of no audio.

If I install jigasi package 1.0-104 (and purge my custom configs from before), I do get audio (but not encrypted).

I also see in the jigasi logs a bunch of these error messages:

2016-05-19 20:38:43.207 SEVERE: [152] org.jitsi.impl.neomedia.RTPConnectorInputStream.error() Failed to receive a packet: 
java.lang.IllegalArgumentException: Impossible Exception
	at net.sf.fmj.media.rtp.RTCPPacketParser.parse(RTCPPacketParser.java:441)
	at org.jitsi.impl.neomedia.rtcp.RTCPPacketParserEx.parse(RTCPPacketParserEx.java:80)
	at org.jitsi.impl.neomedia.transform.rtcp.StatisticsEngine.reverseTransform(StatisticsEngine.java:942)
	at org.jitsi.impl.neomedia.transform.SinglePacketTransformer.reverseTransform(SinglePacketTransformer.java:136)
	at org.jitsi.impl.neomedia.transform.TransformEngineChain$PacketTransformerChain.reverseTransform(TransformEngineChain.java:299)
	at org.jitsi.impl.neomedia.transform.TransformInputStream.createRawPacket(TransformInputStream.java:84)
	at org.jitsi.impl.neomedia.RTPConnectorInputStream.runInReceiveThread(RTPConnectorInputStream.java:810)
	at org.jitsi.impl.neomedia.RTPConnectorInputStream.access$000(RTPConnectorInputStream.java:41)
	at org.jitsi.impl.neomedia.RTPConnectorInputStream$3.run(RTPConnectorInputStream.java:607)


So, am I correct in thinking that the root cause of the issue has not been fixed, and you only disabled ZRTP as a quick and dirty fix to get audio flowing again?

Cheers

**Comment by ibauersachs** [comment]
@petervnv The Videobridge doesn't speak ZRTP. Why would you need that?

**Comment by petervnv** [comment]
@ibauersachs I know jvb doesn't speak zrtp, but jitsi does, and so does my sip server and UACs.
I know I had this setup working properly in the past, with ZRTP audio enabled for SIP using jigasi, so something must have changed.

**Comment by ibauersachs** [comment]
The change you saw in the commit is for the connection between jigasi and the bridge, not between jigasi and the sip server. Is ZRTP encrypted audio still working if you take the account data from your Jigasi sip-communicator.properties to Desktop Jitsi (where you probably configured it in the first place to transfer it)?

Btw: how do you verify the SAS on the server? Without that (and the fact that Jigasi doesn't check TLS certificates) calls are insecure.

**Comment by petervnv** [comment]
I've done some more testing. Desktop jitsi to linphone on iOS works ok (ZRTP is working).
I've copied some of the parameters from jitsi to jigasi and I'm getting mixed results. linphone can hear jigasi/jitmeet and zrtp is working, but it seems jigasi/jitmeet can't hear the linphone UAC (this is likely due to the fact that linphone has ice for SIP while jigasi apparently doesn't). I'll keep exploring and looking through the logs and some sip captures to figure out what is going on.

And re SAS, yes you are correct there's no way to confirm it yet, but I'm working on a solution for that (still, zrtp crypto without sas checking is still better than cleartext anyway). Re jigasi not checking certs, it's also not a big deal in my case since the sip proxy is on the same network as jigasi, so the chances of MiTM a local connection is a negligible risk.

**Comment by ToniIltanen** [comment]
Any progress on this? I have this issue on the latest jigasi package on ubuntu. 
Calls work, but no audio.
```
SEVERE: [602] net.sf.fmj.media.Log.error()   Unable to handle format: LINEAR, 48000.0 Hz, 16-bit, Mono, LittleEndian, Signed
```

**Comment by Franco-Sparrow** [comment]
Hi @damencho does jigasi still works without video or new version supports audio/video meetings with SIP clients?

**Comment by damencho** [comment]
Jigasi is audio only and that will not change.

**Comment by Strouroul** [comment]
there is no audio even coming from the calls in Jigasi

SIP is registered 

Jigasi works fine with transcriber



so in the call the SIP call works fine and when accepted the user enters the meeting but no audio or video is going from or to the call ?

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.
