### ISSUE TITLE
Subtitles must be "forced" to be diplayed

### ISSUE THREAD

**Issue by irossett** [jitsi/jigasi#343]
## Current behavior

Close caption control is showed only for authenticated user or  moderator.
So the first step is stop using an anonymous auth.
After that, CC button is showed but if we click it button nothing appears.

We need to insert in developer console:

`APP.conference._room.setLocalParticipantProperty('transcription_language','it-IT');`

(or another language) to see the subtitles.

We tried on focal fossa with stable and unstable release (  1.1-173-g256efc1-1  )

Thanks.

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues, thank you.

Only moderators/authenticated user can turn on caption, that's why the button is visible only to those participants before the feature is turned on. After it is turned on in a conference, there is a visual indication that this is ongoing and the rest of the participants can turn them on if they want.
